### ISSUE TITLE
Error shows at the end... but it doesn't affect game play.

### ISSUE THREAD

**Issue by pbateman828** [CarolinaIgnites/gameFrame#11]
I was fixing potential copyright issues by renaming and putting new images in. This error only comes up after the game is finished. When the score and highscore are displayed at the end. 

physicsjs-full.min.js:11 Uncaught TypeError: Cannot read property 'emit' of null
    at d.(anonymous function).render (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:11:8806)
    at f.render (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:9:31609)
    at https://www.carolinaignites.org/assets/js/gameframe.js:335:23
    at f.emit (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:9:16538)
    at f.step (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:9:31425)
    at https://www.carolinaignites.org/assets/js/gameframe.js:344:27
    at emit (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:9:16538)
    at d (https://cdnjs.cloudflare.com/ajax/libs/PhysicsJS/0.7.0/physicsjs-full.min.js:9:16885)
render @ physicsjs-full.min.js:11
render @ physicsjs-full.min.js:9
(anonymous) @ gameframe.js:335
emit @ physicsjs-full.min.js:9
step @ physicsjs-full.min.js:9
(anonymous) @ gameframe.js:344
emit @ physicsjs-full.min.js:9
d @ physicsjs-full.min.js:9

**Comment by dmadisetti** [comment]
Hmm. Unable to replicate, so closing out
